version: "3"
services:
  postgres-db:
    image: dbase
    build:
      context: ./database
      dockerfile: Dockerfile
    expose:
      - "5432"
  flask-backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on: 
      - postgres-db
  django-client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - flask-backend

