
Vagrant.configure(2) do |config|
 


  config.vm.define "master" do |master|
    master.vm.box = "debian/jessie64"

   master.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end

  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "debian/jessie64"

   slave.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end

  end
 

 
end
