
Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
 
  # config.vm.provision "shell", inline: <<-SHELL
  #  apt-get update -y
  # SHELL
  
  config.vm.provision :docker
  
  config.vm.provision "shell", inline: "usermod -aG docker $(whoami)"

  config.vm.provision :docker_compose, rebuild: true, run: "always", yml: "/vagrant/docker/docker-compose.yml"
end
