version: "3"
services:
  postgres-db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  flask-backend:
    image: advorzhak/ss_ita_task_0:0.0.1
    environment:
      - FLASK_APP=/backend/app.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    depends_on: 
      - postgres-db
    command: ["sh", "/backend/flask_run.sh"]
  django-frontend:
    image: advorzhak/ss_ita_task_0:0.0.1
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/frontend
    depends_on: 
      - flask-backend
    command: ["sh", "/frontend/django_run.sh"]
volumes:
  backend:
  frontend:
